Updating help site paths to be full urls & adding ability to use static urls if passed through from contentful
sharesight/help.sharesight.com pull request #191
Opened 2023-07-27 11:48 UTC by maisiembleton

2023-07-27 21:24 UTC, alto reviewed
This LGTM in general, I just don't know where the `static_url_slug` is coming from.

2023-07-27 21:24 UTC, alto commented on helpers/middleman/collection.rb
> +    if page[:static_url_slug]
Where does `page[:static_url_slug]` come from?

2023-07-27 22:13 UTC, alto commented on helpers/middleman/collection.rb
> +    return  page_url(page, locale_id: locale_id, base_url: config[:base_url])
```suggestion
    page_url(page, locale_id: locale_id, base_url: config[:base_url])
```

2023-07-27 22:41 UTC, maisiembleton commented on helpers/middleman/collection.rb
> +    if page[:static_url_slug]
I am going to add an optional field in contentful `static_url_slug` for the help site entries

2023-07-27 22:45 UTC, alto approved these changes

2023-07-28 04:10 UTC, maisiembleton commented
Lil update - have added `static_url_slug` to the content model for help articles and populated it for this help article - https://help.sharesight.com/supported-stock-exchanges-and-managed-funds/  with `static_url_slug: supported-stock-exchanges-managed-funds-mutual-funds` so when users search for the supported markets page in the help site, clicking on the link should take them directly to the static-www page. 

Testing it out locally, this works as expected, will deploy to staging and check again

2023-07-28 05:05 UTC, alto approved these changes

2023-07-28 06:05 UTC, maisiembleton commented
Added some tests for the new functions!

2023-07-28 06:15 UTC, alto requested changes
Tests fail now 😬

2023-08-02 21:20 UTC, alto approved these changes
💯

2023-08-10 00:05 UTC, merged